# Generated by Django 5.1.5 on 2025-02-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb_robot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variable',
            name='nb_robot_variable_unique_variable_name',
        ),
    ]
