# Generated by Django 5.1.5 on 2025-02-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb_robot', '0003_remove_resource_nb_robot_resource_unique_resource_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='nb_robot_resource_unique_resource_slug',
        ),
    ]
